services:
  backend:
    build:
      context: ./todo_list_sap_case
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      - ALLOWED_ORIGIN=http://localhost:3000
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./todo_list_sap_case_frontend/my-todo-list
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - backend
